Route.MVCProject.PL/Models/ErrorViewModel.cs
namespace Route.MVCProject.PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Route.MVCProject.PL/ViewModels/ErrorViewModel.cs
namespace Route.MVCProject.PL.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Route.MVCProject.PL/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Route.MVCProject.BLL.Interfaces;
using Route.MVCProject.DAL.Models;

namespace Route.MVCProject.PL.Controllers
{
    // Inheritance: DepartmentController is a Controller
    // Composition: DepartmentController has an object from class Implementing IDepartmentRepository
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository departmentRepo;

        public DepartmentController(IDepartmentRepository _departmentRepo) // ASK CLR For an object Implementing IDepartmentReopsitory Interafce
        {
            departmentRepo = _departmentRepo;
        }

        [HttpGet]// "BaseUrl/Department/Index"
        public IActionResult Index()
        {
            var Departments = departmentRepo.GetAll();
            return View(Departments);
        }

        [HttpGet] // GET : "BaseUrl/Department/Create"
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // POST : "BaseUrl/Department/Create"
        public IActionResult Create(Department departament)
        {
            if(ModelState.IsValid)
            {
               var count = departmentRepo.Add(departament);

                if(count > 0)
               return RedirectToAction(nameof(Index));
            }
            return View(departament);
        }
    }
}

Route.MVCProject.PL/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Route.MVCProject.PL.ViewModels;

namespace Route.MVCProject.PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Route.MVCProject.PL/Views/Department/Create.cshtml
@model Department
@{
    ViewData["Title"] = "Create";
}

<div class="my-3">
    <h1>Create New Department</h1>
</div>
<form class="d-flex flex-column gap-4" asp-action="Create">
    <div class="form-group">
        <label class="form-label" asp-for="Code"></label>
        <input class="form-control" asp-for="Code"/>
        <span class="text-danger text-capitalize" asp-validation-for="Code"></span>
    </div>   
    <div class="form-group">
        <label class ="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger text-capitalize" asp-validation-for="Name"></span>
    </div>    
    <div class="form-group">
        <label class="form-label"  asp-for="CreationDate"></label>
        <input type="date" class="form-control" asp-for="CreationDate" />
    </div>
    <div class="form-group mt-4 d-flex justify-content-end gap-3">
        <input type="submit" class="btn btn-primary" value="Create Department"/>
        <a class="btn btn-danger" asp-action="Index"><i class="fa-solid fa-arrow-right-to-bracket me-2"></i> Go Back</a>
    </div>
</form>

Route.MVCProject.PL/Views/Department/Index.cshtml
@model IEnumerable<Department>

@{
    ViewData["Title"] = "Index";
}

<section class="d-flex justify-content-between align-items-center my-5">
    <h1><i class="fa-regular fa-building me-2"></i> Departments</h1>

    <p>
        <a class="btn btn-outline-primary" asp-action="Create">Create New</a>
    </p>

</section>
@if(Model.Any())
{
    <table class="table table-striped table-hover table-active table-dark text-center">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreationDate)
                </th>
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="align-content-center">
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td class="align-content-center"> 
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="align-content-center">
                        @Html.DisplayFor(modelItem => item.CreationDate)
                    </td>
                    <td>
                        <a class="btn btn-outline-warning" asp-controller="Department" asp-action="Details" asp-route-id="@item.Id"><i class="fa-solid fa-eye me-2"></i>Details</a>
                    </td>                    
                    <td>
                        <a class="btn btn-outline-info" asp-controller="Department" asp-action="Update" asp-route-id="@item.Id"><i class="fa-regular fa-pen-to-square me-2"></i>Update</a>
                    </td>                  
                    <td>
                        <a class="btn btn-outline-danger" asp-controller="Department" asp-action="Delete" asp-route-id="@item.Id"><i class="fa-regular fa-trash-can me-2"></i>Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <section class="alert alert-info fs-5">
        <i class="fa-solid fa-circle-exclamation me-2"></i> There are no Departments
    </section>
}

Route.MVCProject.PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Route.MVCProject.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Route.MVCProject.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Route.MVCProject.PL.styles.css" asp-append-version="true" />
	@* <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" /> *@
	<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Route.MVCProject.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Route.MVCProject.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/font-awesome/js/all.js"></script> *@
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>